import * as vscode from 'vscode';

export class ResultPanel {
  private static panels: Map<string, vscode.WebviewPanel> = new Map();

  static show(title: string, markdown: string, context: vscode.ExtensionContext): void {
    const key = title;
    const existing = ResultPanel.panels.get(key);

    if (existing) {
      existing.reveal(vscode.ViewColumn.Beside);
      existing.webview.html = ResultPanel.buildHtml(title, markdown);
      return;
    }

    const panel = vscode.window.createWebviewPanel(
      'plcAIResult',
      title,
      vscode.ViewColumn.Beside,
      { enableScripts: false, retainContextWhenHidden: true }
    );

    panel.webview.html = ResultPanel.buildHtml(title, markdown);
    ResultPanel.panels.set(key, panel);

    panel.onDidDispose(() => {
      ResultPanel.panels.delete(key);
    });
  }

  private static buildHtml(title: string, markdown: string): string {
    const escaped = markdown
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

    // Simple markdown-like rendering for the webview
    const html = escaped
      .replace(/^## (.+)$/gm, '<h2>$1</h2>')
      .replace(/^### (.+)$/gm, '<h3>$1</h3>')
      .replace(/^#### (.+)$/gm, '<h4>$1</h4>')
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/^- (.+)$/gm, '<li>$1</li>')
      .replace(/^(\d+)\. (.+)$/gm, '<li><strong>$1.</strong> $2</li>')
      .replace(/\n\n/g, '</p><p>')
      .replace(/(<li>[\s\S]*?<\/li>)/g, '<ul>$1</ul>')
      .replace(/^```[\s\S]*?```$/gm, (match) => {
        const code = match.replace(/^```\w*\n?/, '').replace(/\n?```$/, '');
        return `<pre><code>${code}</code></pre>`;
      });

    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${title}</title>
<style>
  :root {
    --bg: var(--vscode-editor-background);
    --fg: var(--vscode-editor-foreground);
    --border: var(--vscode-panel-border);
    --code-bg: var(--vscode-textCodeBlock-background);
    --heading: var(--vscode-textLink-foreground);
    --strong: var(--vscode-symbolIcon-keywordForeground);
  }
  body {
    font-family: var(--vscode-font-family);
    font-size: 13px;
    line-height: 1.6;
    color: var(--fg);
    background: var(--bg);
    padding: 20px 24px;
    max-width: 900px;
  }
  h1 { font-size: 1.4em; color: var(--heading); border-bottom: 1px solid var(--border); padding-bottom: 8px; }
  h2 { font-size: 1.15em; color: var(--heading); margin-top: 24px; border-left: 3px solid var(--heading); padding-left: 8px; }
  h3 { font-size: 1em; color: var(--heading); margin-top: 16px; }
  h4 { font-size: 0.95em; margin-top: 12px; }
  code { background: var(--code-bg); padding: 1px 5px; border-radius: 3px; font-family: var(--vscode-editor-font-family); font-size: 12px; }
  pre { background: var(--code-bg); padding: 12px; border-radius: 4px; overflow-x: auto; border: 1px solid var(--border); }
  pre code { background: none; padding: 0; }
  table { border-collapse: collapse; width: 100%; margin: 12px 0; font-size: 12px; }
  th { background: var(--code-bg); border: 1px solid var(--border); padding: 6px 10px; text-align: left; }
  td { border: 1px solid var(--border); padding: 5px 10px; vertical-align: top; }
  ul, ol { padding-left: 20px; }
  li { margin: 3px 0; }
  strong { color: var(--strong); }
  .meta { color: var(--vscode-descriptionForeground); font-size: 11px; margin-bottom: 16px; }
  hr { border: none; border-top: 1px solid var(--border); margin: 20px 0; }
</style>
</head>
<body>
<h1>${title}</h1>
<div class="meta">Generated by PLC AI Assistant · ${new Date().toLocaleString()}</div>
<hr>
<p>${html}</p>
</body>
</html>`;
  }
}
